### ISSUE TITLE
Cant get label

### ISSUE THREAD

**Issue by Savrov** [Pernifloss/ImageMap#3]
Hi, thanks for an awesome lib! 
Could you check code if there is no problems with labels? I followed [your code](https://github.com/Pernifloss/ImageMap/tree/master/app/src/main/java/com/zechassault/cimi/imagemap/anatomy), but cant get display them.

Second question, would you implement custom ui for lables, for ex. I want to use a CardView  for labels decoration.

Thanks you again.

**Comment by Pernifloss** [comment]
The library only work with Bitmap for clickable image.
