### ISSUE TITLE
Can't implement dependencies

### ISSUE THREAD

**Issue by StefanKarasmilov** [Pernifloss/ImageMap#5]
Hello.

The library looks fantastic, but I have some problems when I want to implement the dependencies compile 'com.github.Pernifloss:ImageMap:0.4.1' the Gradle can't resolve it. 

There is something more to do so the Gradle can compile it?

Thank You!

**Comment by Pernifloss** [comment]
i tryied just now, it works if you add jitpack to your repository 

```
allprojects {
    repositories {
        ...
        maven {
            url "https://jitpack.io"
        }
    }
}

```
And then add.

```
dependencies {
     ...
    implementation 'com.github.Pernifloss:ImageMap:0.4.1'
}
```
in your build app buikd.gadle.
